package betagame;
//this class creates a gui visible during the gameplay
//shows score and counts
//gives option of Restart, Pause, Exit
import city.cs.engine.*;
import java.awt.Color;
import java.awt.Graphics;
import javax.swing.JFrame;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

public class ControlPanel extends javax.swing.JPanel implements ChangeListener{

    private JFrame frame;
    private GameLevel world; 
    private UserView view;
    private BallPlayer ball;
    private BetaGame game;

    public ControlPanel(JFrame frame, UserView view, GameLevel world,BallPlayer ball, BetaGame game) {
        initComponents();
        this.frame = frame;
        this.view = view;
        this.world = world;
        this.ball = ball;
        this.game = game;
        ball.addChangeListener(this);
        
    }
    public void setWorld(GameLevel world){
        this.world = world;
    }

    public void setBall(BallPlayer ball) {
        this.ball = ball;
        ball.addChangeListener(this);
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        scoreLabel.setText("Score : "+ball.getStarCount());
        boostLabel.setText("Boosts : "+ball.getBoostCount());
        jumpLabel.setText("Jumps : "+ball.getJumpCount());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pauseButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        restartButton = new javax.swing.JButton();
        scoreLabel = new javax.swing.JLabel();
        boostLabel = new javax.swing.JLabel();
        jumpLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 102, 102));
        setPreferredSize(new java.awt.Dimension(281, 47));

        pauseButton.setBackground(new java.awt.Color(204, 204, 204));
        pauseButton.setFont(new java.awt.Font("DigifaceWide", 0, 18)); // NOI18N
        pauseButton.setForeground(new java.awt.Color(204, 0, 0));
        pauseButton.setText("Pause");
        pauseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseButtonActionPerformed(evt);
            }
        });

        exitButton.setBackground(new java.awt.Color(204, 204, 204));
        exitButton.setFont(new java.awt.Font("DigifaceWide", 0, 18)); // NOI18N
        exitButton.setForeground(new java.awt.Color(204, 0, 0));
        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        restartButton.setBackground(new java.awt.Color(204, 204, 204));
        restartButton.setFont(new java.awt.Font("DigifaceWide", 0, 18)); // NOI18N
        restartButton.setForeground(new java.awt.Color(204, 0, 0));
        restartButton.setText("Restart");
        restartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restartButtonActionPerformed(evt);
            }
        });

        scoreLabel.setFont(new java.awt.Font("DigifaceWide", 0, 14)); // NOI18N
        scoreLabel.setForeground(new java.awt.Color(255, 255, 51));
        scoreLabel.setText("score");

        boostLabel.setFont(new java.awt.Font("DigifaceWide", 0, 14)); // NOI18N
        boostLabel.setForeground(new java.awt.Color(0, 102, 255));
        boostLabel.setText("boost");

        jumpLabel.setFont(new java.awt.Font("DigifaceWide", 0, 14)); // NOI18N
        jumpLabel.setForeground(new java.awt.Color(102, 255, 0));
        jumpLabel.setText("jump");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(417, 417, 417)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scoreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(boostLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jumpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(restartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pauseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(scoreLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(boostLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jumpLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(restartButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pauseButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(exitButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pauseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauseButtonActionPerformed
        if (!world.isPaused()){
            world.setPaused(true);
            pauseButton.setText("Resume");
            frame.removeKeyListener(game.getController());
        }
        else{
            world.setPaused(false);
            pauseButton.setText("Pause");
            frame.addKeyListener(game.getController());
        }
       
    
        
    }//GEN-LAST:event_pauseButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void restartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restartButtonActionPerformed
        if(game.getLevelNum()==0){
            game.getLevels().remove(game.getLevelNum());
            game.getLevels().add(game.getLevelNum(),new Level1(game));
        }
        if(game.getLevelNum()==1){
            game.getLevels().remove(game.getLevelNum());
            game.getLevels().add(game.getLevelNum(),new Level2(game));
        }
        if(game.getLevelNum()==2){
            game.getLevels().remove(game.getLevelNum());
            game.getLevels().add(game.getLevelNum(),new Level3(game));
        }
        game.getActor().setStarCount(0);
        game.changeLevel();
    }//GEN-LAST:event_restartButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel boostLabel;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jumpLabel;
    private javax.swing.JButton pauseButton;
    private javax.swing.JButton restartButton;
    private javax.swing.JLabel scoreLabel;
    // End of variables declaration//GEN-END:variables


    @Override
    public void stateChanged(ChangeEvent ce) {
        repaint();
    }   
    
    
}
